version: '3.8'
services:
  db: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - app

  app:
    command: [ 'sh' , '-c' , 'yarn install && yarn postinstall && npx prisma db push && yarn dev' ]
    build: ./app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./app:/usr/src/app:rw